services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
      - academic-service
      - finance-service
      - hr-service

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    expose:
      - "8001"
    environment:
      AUTH_DB_HOST: mysql
      AUTH_DB_PORT: 3306
      AUTH_DB_NAME: school_erp
      AUTH_DB_USER: erp_user
      AUTH_DB_PASSWORD: erp_password_change_me
    depends_on:
      - mysql

  academic-service:
    build:
      context: .
      dockerfile: academic-service/Dockerfile
    expose:
      - "8002"

  finance-service:
    build:
      context: .
      dockerfile: finance-service/Dockerfile
    expose:
      - "8003"

  hr-service:
    build:
      context: .
      dockerfile: hr-service/Dockerfile
    expose:
      - "8004"

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: school_erp
      MYSQL_USER: erp_user
      MYSQL_PASSWORD: erp_password_change_me
      MYSQL_ROOT_PASSWORD: root_password_change_me
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/001-schema.sql:ro

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  mysql-data:
  rabbitmq-data:
